_core:
  default_config_hash: 4GIX5Esnc_umpXUBj4IIocRX7Mt5fPhm4AgXfE3E56E
module:
  address: 0
  announcements_feed: 0
  antibot: 0
  automated_cron: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor5: 0
  coffee: 0
  comment: 0
  config: 0
  content_moderation: 0
  contextual: 0
  crop: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  diff: 0
  dynamic_page_cache: 0
  editor: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  focal_point: 0
  geolocation: 0
  geolocation_address: 0
  geolocation_leaflet: 0
  gin_toolbar: 0
  help: 0
  history: 0
  honeypot: 0
  image: 0
  jquery_ui: 0
  jquery_ui_autocomplete: 0
  jquery_ui_menu: 0
  language: 0
  layout_builder: 0
  layout_discovery: 0
  link: 0
  linkit: 0
  media: 0
  media_entity_download: 0
  media_file_delete: 0
  media_library: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  metatag_open_graph: 0
  mysql: 0
  navigation: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  quick_node_clone: 0
  redirect: 0
  scheduler: 0
  search: 0
  shortcut: 0
  simple_sitemap: 0
  smart_date: 0
  sqlite: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  uli_custom_workflow: 0
  update: 0
  user: 0
  views_ui: 0
  webform: 0
  webform_ui: 0
  workflows: 0
  pathauto: 1
  content_translation: 10
  views: 10
theme:
  olivero: 0
  claro: 0
  gin: 0
